repos:
-   repo: https://github.com/DoodleScheduling/pre-commit-config-updater
    rev: master
    hooks:
    - id: pre-commit-config-updater
      additional_dependencies: [tomlkit]
      always_run: true
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
      args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   repo: https://github.com/godaddy/tartufo
    rev: v3.1.2
    hooks:
    - id: tartufo
      language: python
      args: [pre-commit]
